### PR TITLE
Added clear function

### PR DESCRIPTION
**Pull request by TheDataLeek**
"clear" function now part of XYPlot. This function sets the plot's data series to an empty array and initializes a new view with Node().

### CODE REVIEW

**Comment by pixelzoom** [comment]
@ariel-phet Here's a pull request that someone needs to evaluate.

**Comment by TheDataLeek** [comment]
(Some Background)

I'm working with Emily Randall on the quantum bound states sim. I'm currently trying to expand the functionalities of griddle so that it supports animated plots with decent performance. This pull requests serves two purposes. I've added this function in my `dev` branch, and it notifies you guys that I'm working on this.

Please let me know if my implementation goes against current standards or if it has unexpected side effects.

**Comment by pixelzoom** [comment]
Hi Will, 

Thanks for the introduction and clarification, that helps us to prioritize your pull request. Someone will review your work before merging. For future reference, the "Code Style Guidelines" section of the "PhET Development Overview" (http://bit.ly/phet-development-overview) describes some criteria that will be used to evaluate your code. Let us know if you have any questions about that.

Chris

**Comment by samreid** [comment]
@willzfarmer I'm excited that you are working on the quantum bound states sim and willing to help out with our immature "griddle" library.  I'll take a look through your change sets and let you know my thoughts.

**Comment by samreid** [comment]
It looks like there are several commits in the pull request history that are transient--changes that were made in the fork then reverted.  For example ac2e0eb8e0e6d274e6efc48f17d06b15aa148217 introduces this function into XYDataSeries.js:

``` js
    setPoints: function(xarr, yarr) {
      this.clear();
      for (var j=0; j < xarr.length; j++) {
          this.addPoint(xarr[j], yarr[j]);
      }
    }
```

Then in 5060461a0ccb46f523fa4548cfe4f512100c99b0 this function is removed.

I noticed this sort of transient commit for several features, including XYDataSeries.setPoints, XYDataSeries.range and griddle-main's step function.  

In the future, pull requests should not contain any transient changes--they make the history more difficult to understand and reviewing the pull request more difficult.

I'll continue my review in the next comment.

**Comment by samreid** [comment]
After ignoring transient changes (described in the previous comment), there are only two changes for this pull request:
1. Changing the default width of the XYPlot from 400 to 402.  This seems unnecessary and no explanation is given.  Perhaps a typo?
2. XYPlot.js has a new function, implemented like so:

``` js
    clear: function() {
        this.series = []
        this.content = new Node();
    }
```

Simply recreating the content node here is unlikely to have the intended consequence--the former content node is still registered with the parent Panel, and hasn't been removed.  This would also clear the axis arrows, even if the new content Node was registered with the Panel.

It seems like the desired behavior would be to remove the series Lines added in this code:

``` js
    addSeries: function( series ) {
      this.series.push( series );
      var xyPlot = this;
      series.addDataSeriesListener( function( x, y, xPrevious, yPrevious ) {
        if ( xPrevious && yPrevious && (xPrevious !== 0 || yPrevious !== 0 ) ) {
          xyPlot.content.addChild( new Line( xPrevious, yPrevious, x, y, { stroke: series.color } ) );
        }
      } );
    }
```

In that case, we will need to keep track of the Line instances added by different series instances.  And then it would probably make more sense to have a removeSeries() function.

One last issue, there is a `;` missing from the array assignment line, which could cause jshint for a simulation to fail (you can test this with npm install then grunt for a simulation if griddle is properly listed as a dependency in package.json) or with npm install then grunt lint for griddle just to test griddle.

I'll leave this issue open for discussion, but we will not be able to accept this pull request.  Please let me know if you have any questions or comments, and create a new pull request if you wish to continue.

Best Regards,
Sam

**Comment by TheDataLeek** [comment]
Thank you for your feedback.
1. I apologize for the transient commits, I tried to remove those as much as possible but obviously failed.
2. The width adjustment is a typo.
3. I see what you're saying about the removeSeries() function. That makes more sense.

I will mark this pull request as closed because of errors, typos, and a misguided feature. I will try to come back with a better `removeSeries()` function.

**Comment by samreid** [comment]
Perfect, thanks @willzfarmer, I look forward to it!

**Pull request closed without merging**
