### PR TITLE
removeSeries Function

### PR DESCRIPTION
**Pull request by TheDataLeek**
Added `removeSeries` function to XYPlot. This is comprised of two main parts.
1. The DataSeries listener now pushes the Line object it creates to a instance array called `lines`.
2. The `removeSeries` function removes the series from the series array and also removes every child Line object that has been added by the listener from the plot.

The end result is that I was able to make a "moving" line by adding and removing these series. I will work on incorporating that code in a sane way.

### CODE REVIEW

**Comment by samreid** [comment]
PhET requires signature of a Contributor License Agreement before accepting a significant amount of code for this library.  I didn't have @willzfarmer's email address but sent an email via @EmilyRandall.

**Comment by samreid** [comment]
The way the changes are organized above stores individual line segments for each series like so:

``` js
    addSeries: function( series ) {
      this.series.push( series );
      var xyPlot = this;
      series.addDataSeriesListener( function( x, y, xPrevious, yPrevious ) {
        if ( xPrevious && yPrevious && (xPrevious !== 0 || yPrevious !== 0 ) ) {
          var line = new Line( xPrevious, yPrevious, x, y, { stroke: series.color } );
          xyPlot.content.addChild(line);
          series.lines.push(line);
        }
      } );
    }
```

Perhaps it would be even better to create a single Node for each series, then removing the data series would be a simple as removing the Node.  I'll take a look into it momentarily.

**Comment by samreid** [comment]
Also XYDataSeries.setPoints was suggested as:

``` js
    setPoints: function(xarr, yarr) {
      this.clear();
      for (var j=0; j < xarr.length; j++) {
          this.addPoint(xarr[j], yarr[j]);
      }
    }
```

However, I think it would be more consistent with the rest of the PhET ecosystem to use setPoints:function(vectorArray) as the signature instead of array/array.

**Comment by samreid** [comment]
I committed what I envisioned for XYPlot.removeSeries in #14.  @willzfarmer can you take a look and let me know if it will work for your project?

**Comment by TheDataLeek** [comment]
Yeah, this looks good. What are your thoughts on the XYDataSeries utilities? The setPoints function in particular seems important and may possibly be able to work with #8 in making a smooth path object instead of many Line objects.

**Pull request closed without merging**
